language: python
python:
  - 2.7
  - pypy

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-gpod

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install --editable .

script: mamba
