language: python
python:
  - 2.7

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-gpod

install:
  - pip install --editable .
  - pip install -r dev-requirements.txt

script: mamba
